### ISSUE TITLE
Plans for viz module

### ISSUE THREAD

**Issue by Garyfallidis** [nipy/dipy#1544]
Here some ideas for moving forward with the viz module. These are the notes after a call that I had with @MarcCote.

- [ ]  Currently the UI elements have on_xxx callbacks as attributes that can be set any time. We would like to have something similar for all the different actors too. For now you can connect an actor and it's callback using ShowManager.iren.add_callback. 

- [ ]  Timer_callbacks are currently added at the level of the ShowManager (see PR #1528). It maybe beneficial for simplicity to add a the generic add_callback function at the level of ShowManager rather iren.

- [ ]  Hovering event is currently not working very well. Needs some thinking.

- [x] Splitting of the viz module is scheduled for the next coming weeks and definitely before release 0.15.
@skoudoro and myself will lead the split. New project name is currently pending. Let us know if you have ideas.

- [ ] @karandeepSJ, @ranveeraggarwal and @naveenkumarmarri will have to update their PRs after recent merge of #1492 

- [ ] Simple image and track interface will be added by @garyfallidis

- [ ] The grid system will be added by @MarcCote.

- [ ] A 3D orbital menu needs to be refactored by @ranveeraggarwal 

- [ ] Shaders will be added by @dmreagan, @thechargedneutron and myself. Others more than welcome to contribute.

- [ ] The record events mechanism in tests needs to be reconsidered. It is currently difficult to replicate the test. Maybe we should be using our own timer_callbacks (see tests of #1528) . Will have to put some use cases down and see what we can get.

- [x] Support for old vtk versions (< vtk 8.1) should be removed. With the new PYPI installers for VTK packaging is much easier.  And the code can become simpler.

@MarcCote and all, update here if we some information is missing.

**Comment by skoudoro** [comment]
This issue was moved to fury-gl/fury#33
